// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DAHnXvRRg9PhrhHiHxkMIYU5TmlH3gU',
    appId: '1:975247834061:web:19bd1cde679619efb0a284',
    messagingSenderId: '975247834061',
    projectId: 'chatify-3db6a',
    authDomain: 'chatify-3db6a.firebaseapp.com',
    storageBucket: 'chatify-3db6a.firebasestorage.app',
    measurementId: 'G-QYRXL70N47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8k7BBQ3TKRWE2WgAy9gTf9ARukgK-dOo',
    appId: '1:975247834061:android:b9bac11901de28ceb0a284',
    messagingSenderId: '975247834061',
    projectId: 'chatify-3db6a',
    storageBucket: 'chatify-3db6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWh5kpHCCJSUrxEviRIDN41_zDz0Mq7Xg',
    appId: '1:975247834061:ios:5cae3036b9b7e09eb0a284',
    messagingSenderId: '975247834061',
    projectId: 'chatify-3db6a',
    storageBucket: 'chatify-3db6a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWh5kpHCCJSUrxEviRIDN41_zDz0Mq7Xg',
    appId: '1:975247834061:ios:5cae3036b9b7e09eb0a284',
    messagingSenderId: '975247834061',
    projectId: 'chatify-3db6a',
    storageBucket: 'chatify-3db6a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DAHnXvRRg9PhrhHiHxkMIYU5TmlH3gU',
    appId: '1:975247834061:web:4ed174377921034cb0a284',
    messagingSenderId: '975247834061',
    projectId: 'chatify-3db6a',
    authDomain: 'chatify-3db6a.firebaseapp.com',
    storageBucket: 'chatify-3db6a.firebasestorage.app',
    measurementId: 'G-JWPT7G6PGM',
  );
}
